### ISSUE TITLE
Restrict access to the Transaction endpoints

### ISSUE THREAD

**Issue by jtherrmann** [ASFHyP3/asf-stac#2]
# Overview

The [Transaction extension](https://github.com/radiantearth/stac-api-spec/blob/v1.0.0-rc.1/ogcapi-features/extensions/transaction/README.md) supports creating, updating, and deleting items. I assume we want to restrict these endpoints to the Tools team?

**Edit:** Although we've restricted access at the database layer, it would still be nice to remove those endpoints from the API itself, both for extra security and so as not to confuse users who see those endpoints available in the Swagger UI. The problem is that currently we're using the app provided [here](https://github.com/stac-utils/stac-fastapi/blob/master/stac_fastapi/pgstac/stac_fastapi/pgstac/app.py), and there doesn't seem to be an easy way to just disable particular extensions from an already-created app. One option is to do all of that configuration in our lambda handler, but if the `stac-fastapi` developers make significant changes to how they're configuring the app, we won't know about it. Another option is to fork their repo and remove the Transaction extension in our fork, so that we could easily merge upstream changes. Another option is to find some gross non-standard way of disabling the extension in the imported module, such as mocking out the extension.

I assume the `stac-fastapi` devs intend for people to configure and create their own apps as needed, using the modules documented [here](https://stac-utils.github.io/stac-fastapi/), so maybe that's the best way to go.

**Edit 2:** I've opened https://github.com/stac-utils/stac-fastapi/issues/492 to ask the `stac-fastapi` devs for their recommended approach. We could also potentially fork their repo, implement an option to disable the extension, and open a PR to merge the option upstream, so that we wouldn't have to rely on our fork forever.

# Tasks

- [x] The AWS-hosted API should login to the database with read-only permissions
- [x] The `make run-api` command should still login to the database with read-write permissions.
- [x] See <https://stac-utils.github.io/pgstac/pgstac/> for documentation on roles
- [x] Document in the README how to run the API locally for accessing the Transaction endpoints.

**Comment by jtherrmann** [comment]
If we can't require authorization for specific endpoints, perhaps we could provide a public API without the Transaction extension, and a private (Tools team only) API with the extension, and connect them to the same backend database?

**Comment by jtherrmann** [comment]
I asked about this in https://gitter.im/SpatioTemporal-Asset-Catalog/Lobby. If I don't get any helpful responses and there doesn't appear to be a way to do this after further investigation of the STAC API spec and the `stac-fastapi` docs, maybe we can set up some sort of proxy API for managing authorization for specific endpoints?

**Comment by jtherrmann** [comment]
I'm not seeing an obvious way to disable the Transaction Extension in an app that's already been created (we're using the provided `pgstac` app), but I asked about it in the Gitter channel.

**Comment by jtherrmann** [comment]
After modifying the AWS-hosted API to log in as the `pgstac_read` user, I'm now getting a permission denied error for all `/collections/*` endpoints, even when making a `GET` request. I wonder if disabling the Transaction Extension would help?

**Comment by jtherrmann** [comment]
I confirmed that:

* the AWS-hosted API (connected to the database via the `pgstac_read` user) can access all of the non-Transaction endpoints, and that it cannot create or delete collections (though I didn't test the other Transaction endpoints).
* the `pgstac_read` user has only the `SELECT` privilege for all of the `_items_*` tables and the `collections` table.
* the local API (connected to the database via the `postgres` user) can create and delete collections (though I didn't test the other Transaction endpoints).

**Comment by jhkennedy** [comment]
A relevant comment in the [STAC gitter](https://gitter.im/SpatioTemporal-Asset-Catalog/Lobby?at=6373b4b9abfb5860bb1967ba) I'm putting here for posterity:
> We have been demoing authentication & authorization layer as a dependency to a FastAPI app at one of the previous OGC code sprints. Find an example for pygeoapi at https://github.com/geobeyond/fastgeoapi/tree/develop

doesn't look like anything stable enough for us but might be worth looking at in more detail
