### ISSUE TITLE
Automate installing/upgrading PostGIS and PgSTAC

### ISSUE THREAD

**Issue by jtherrmann** [ASFHyP3/asf-stac#9]
# Overview

We should automate installing and upgrading both PostGIS and PgSTAC in the STAC API database.

To install PostGIS for the first time, run the following Postgres command:

```
CREATE EXTENSION postgis;
```

See [here](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Appendix.PostgreSQL.CommonDBATasks.PostGIS.html#Appendix.PostgreSQL.CommonDBATasks.PostGIS.Update) and [here](https://postgis.net/workshops/postgis-intro/upgrades.html) for instructions for upgrading PostGIS. We'll want to upgrade to a specific version (rather than just upgrading to the latest version).

To install PGStac into the database:

```
make migrate db_host=<host> db_password=<password>
```

After upgrading `pypgstac`, you can re-run the above command to upgrade the version of PGStac installed to the database. So for the CICD pipeline, it should be sufficient to install requirements to their pinned versions (including `pypgstac`), then run the `migrate` command, regardless of whether it's a first-time deployment.

For more information about migrations, see <https://stac-utils.github.io/pgstac/pypgstac/>.

# Tasks

- [x] Automate installation and upgrade of PostGIS
- [x] Automate installation and upgrade of PgSTAC
- [x] Test Postgres version upgrade by deploying a stack with older Postgres (and the appropriate version of PostGIS), then upgrading to newer Postgres and PostGIS according to README instructions
